	CREATE DATABASE QLBH
	use QLBH
	--bản update 17:28 09/05

create table GIAY (
	MASP INT NOT NULL PRIMARY KEY,
	TENSP NVARCHAR(100) NOT NULL,
	SOLUONG INT NOT NULL,
	GIABAN INT NOT NULL,
	GIANHAP INT NOT NULL,
	MAU NVARCHAR(50),
	TRANGTHAI NVARCHAR(50) NOT NULL, 
	SIZE FLOAT NOT NULL,
	HANG NVARCHAR(50),
	MALOAI INT NOT NULL,
	image image --NEW
)

create table PHUKIEN (
	MASP INT NOT NULL PRIMARY KEY,
	TENSP NVARCHAR(100) NOT NULL,
	SOLUONG INT NOT NULL,
	GIABAN INT NOT NULL,
	GIANHAP INT NOT NULL,
	MAU NVARCHAR(50),
	TRANGTHAI NVARCHAR(50) NOT NULL,
	THONGSO NVARCHAR(255) NOT NULL,
	GHICHU NVARCHAR(255),
	MALOAI INT NOT NULL,
	image image --NEW
)
	

CREATE TABLE LOAISP(
	MALOAI INT NOT NULL PRIMARY KEY,
	TENLOAI NVARCHAR(100) NOT NULL,
	PHANLOAI NVARCHAR(20) NOT NULL, --GIAY OR PHUKIEN
)

CREATE TABLE KHACHHANG(
	MAKH INT NOT NULL PRIMARY KEY,
	TENKH NVARCHAR(255) NOT NULL,
	DIACHI NVARCHAR(255),
	SDT CHAR(20) NOT NULL,
	GIOITINH NVARCHAR(10) NOT NULL,
	KHTT nvarchar(10)
)


CREATE TABLE NHANVIEN(
	MANV INT NOT NULL PRIMARY KEY,
	TENNV NCHAR(255) NOT NULL,
	GIOITINH NCHAR(20),
	chucvu nvarchar(50) not null,
	SDT CHAR(20) NOT NULL,	
	TK CHAR(255) NOT NULL,
	MK CHAR(255) NOT NULL,
	trangthai nvarchar(100) not null
)
ALTER TABLE   nhanvien
add chucvu nvarchar(50),
	
	tk char(255),
	MK CHAR(255),
	sdt char(20),
	TRANGTHAI NVARCHAR(100);


CREATE TABLE NHACUNGCAP(
	MANCC INT NOT NULL PRIMARY KEY,
	TENNCC NVARCHAR(255) NOT NULL,
	SPCC NVARCHAR(10) NOT NULL,--VỪA THÊM VÀO 20:09 03/05
	DIACHI NVARCHAR(255),
	SDT CHAR(20) NOT NULL,
	
)


CREATE TABLE HOADON(
	MAHD INT NOT NULL PRIMARY KEY,
	NGAYLAP smalldatetime NOT NULL,  --vừa cập nhật 06/05
	TONGTIEN INT NOT NULL,
	MANV INT NOT NULL,
	MAKH INT NOT NULL,
	ghichu nvarchar(255),
	hinhthuc nvarchar(255)
)

CREATE TABLE CTHDGIAY(
	MAHD INT NOT NULL,
	MASP INT NOT NULL,
	SOLUONG INT NOT NULL,
	GIA INT NOT NULL,
)
 

CREATE TABLE CTHDPHUKIEN(
	MAHD INT NOT NULL,
	MASP INT NOT NULL,
	SOLUONG INT NOT NULL,
	GIA INT NOT NULL,
)

CREATE TABLE PHIEUNHAP(
	MAPN INT NOT NULL PRIMARY KEY,
	NGAYLAP smalldatetime NOT NULL,
	TONGTIEN INT NOT NULL,
	MANV INT NOT NULL,
	MANCC INT NOT NULL,
	ghichu nvarchar(255)
)

CREATE TABLE CTPNGIAY(
	MAPN INT NOT NULL,
	MASP INT NOT NULL,
	SOLUONG INT NOT NULL,
	GIA INT NOT NULL,
)

CREATE TABLE CTPNPHUKIEN(
	MAPN INT NOT NULL,
	MASP INT NOT NULL,
	SOLUONG INT NOT NULL,
	GIA INT NOT NULL,
)


CREATE TABLE KHUYENMAI(
	MAKM INT NOT NULL PRIMARY KEY,
	TENKM NVARCHAR(255) NOT NULL,
	HTKM nvarchar(50) NOT NULL,--HÌNH THỨC KM (GIẢM THEO & OR TIỀN)
	MUCKM INT NOT NULL,--MỨC KHUYẾN MÃI
	NGAYBD DATE,
	NGAYKT DATE,
	MOTA NVARCHAR(255),
)
CREATE TABLE CTKHUYENMAI(
	MAKM INT NOT NULL,
	MASP INT NOT NULL,
	TENSP nvarchar (255) not null
)

alter table CTKHUYENMAI add constraint PK_KM_MAKM PRIMARY KEY(MAKM,MASP)

alter table CTHDGIAY add constraint PK_SOHD_MASP2 PRIMARY KEY(MAHD, MASP)
alter table CTHDPHUKIEN add constraint PK_SOHD_MASP1 PRIMARY KEY(MAHD, MASP)


alter table CTPNGIAY add constraint PK_SOPN_MASP12 PRIMARY KEY(MAPN, MASP)
alter table CTPNPHUKIEN add constraint PK_SOPN_MASP1 PRIMARY KEY(MAPN, MASP)


alter table HOADON add constraint FK_HOADON foreign key (MAKH) references KHACHHANG(MAKH)
alter table HOADON add constraint FK_HOADON2 foreign key (MANV) references NHANVIEN(MANV)

alter table PHIEUNHAP add constraint FK_PHIEUNHAP foreign key (MANCC) references NHACUNGCAP(MANCC)
alter table PHIEUNHAP add constraint FK_PHIEUNHAP1 foreign key (MANV) references NHANVIEN(MANV)

alter table CTHDGIAY add constraint FK_CTHD11 foreign key (MAHD) references HOADON(MAHD)
alter table CTHDGIAY add constraint FK_CTHD2 foreign key (MASP) references GIAY(MASP)

alter table CTHDPHUKIEN add constraint FK_CTHD22 foreign key (MAHD) references HOADON(MAHD)
alter table CTHDPHUKIEN add constraint FK_CTHD3 foreign key (MASP) references PHUKIEN(MASP)


alter table CTPNGIAY add constraint FK_CTPN1 foreign key (MAPN) references PHIEUNHAP(MAPN)
alter table CTPNGIAY add constraint FK_CTPN2 foreign key (MASP) references GIAY(MASP)

alter table CTPNPHUKIEN add constraint FK_CTPN123 foreign key (MAPN) references PHIEUNHAP(MAPN)
alter table CTPNPHUKIEN add constraint FK_CTPN3 foreign key (MASP) references PHUKIEN(MASP)

alter table CTKHUYENMAI add constraint FK_KM foreign key (MASP) references GIAY(MASP)
ALTER TABLE CTKHUYENMAI ADD constraint FK_KM2 foreign key (MAKM) references KHUYENMAI(MAKM)


alter table GIAY add constraint FK_GIAY foreign key (MALOAI) references LOAISP(MALOAI)
alter table PHUKIEN add constraint FK_PHUKIEN foreign key (MALOAI) references LOAISP(MALOAI)


insert into HOADON(mahd,NGAYLAP,TONGTIEN,manv,makh) values(9,'12-02-2002 12:02',12000,1,1)
	insert into HOADON(mahd,NGAYLAP,TONGTIEN,manv,makh) values(5,'05/14/2002 12:02',12000,1,1)
    insert into HOADON(mahd,NGAYLAP,TONGTIEN,manv,makh) values(8,'21-06-2002 13:02',24000,1,1)
	insert into HOADON(mahd,NGAYLAP,TONGTIEN,manv,makh) values(7,'15/01/2002 14:02',33000,1,1)
    insert into HOADON(mahd,NGAYLAP,TONGTIEN,manv,makh) values(6,'28/02/2002 15:02',42000,1,1)
    
    --GIAY
    insert into GIAY(MASP,TENSP,SOLUONG,GIABAN,GIANHAP,MAU,TRANGTHAI,SIZE,HANG,MALOAI) 
    VALUES(0,'Air Force 1',1,1200000,800000,'White','Hoạt động',41,'Nike',0)
    insert into GIAY(MASP,TENSP,SOLUONG,GIABAN,GIANHAP,MAU,TRANGTHAI,SIZE,HANG,MALOAI) 
    VALUES(1,'Ultra Boost',1,2100000,1500000,'White','Hoạt động',39,'Adidas',1)
    insert into GIAY(MASP,TENSP,SOLUONG,GIABAN,GIANHAP,MAU,TRANGTHAI,SIZE,HANG,MALOAI) 
    VALUES(2,'Classic',1,3500000,2700000,'Black','Hoạt động',42,'New Balance',2)
    insert into GIAY(MASP,TENSP,SOLUONG,GIABAN,GIANHAP,MAU,TRANGTHAI,SIZE,HANG,MALOAI) 
    VALUES(3,'Superstar',1,1950000,1000000,'White','Hoạt động',36.5,'Adidas',3)
    insert into GIAY(MASP,TENSP,SOLUONG,GIABAN,GIANHAP,MAU,TRANGTHAI,SIZE,HANG,MALOAI) 
    VALUES(4,'Air Max',1,4200000,3500000,'Pink','Không hoạt động',38.5,'Nike',4)
    insert into GIAY(MASP,TENSP,SOLUONG,GIABAN,GIANHAP,MAU,TRANGTHAI,SIZE,HANG,MALOAI) 
    VALUES(5,'Air Force 1',1,1200000,800000,'Black','Không hoạt động',43,'Nike',5)
    
    --PHU KIEN
    insert into PHUKIEN(MASP,TENSP,SOLUONG,GIABAN,GIANHAP,MAU,TRANGTHAI,THONGSO,GHICHU,MALOAI)
    VALUES(0,'Dây giày',3,10000,5000,'White','Hoạt động','120cm','',0)
    insert into PHUKIEN(MASP,TENSP,SOLUONG,GIABAN,GIANHAP,MAU,TRANGTHAI,THONGSO,GHICHU,MALOAI)
    VALUES(1,'DD vệ sinh',2,50000,30000,'','Hoạt động','350ml','',1)
    insert into PHUKIEN(MASP,TENSP,SOLUONG,GIABAN,GIANHAP,MAU,TRANGTHAI,THONGSO,GHICHU,MALOAI)
    VALUES(2,'Dây giày',3,10000,5000,'Black','Không hoạt động','160cm','',2)
    
    --KHACH HANG
    INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,SDT,GIOITINH,KHTT) VALUES(0,'Phan Chí Dũng','TP.HCM','093472005673','Nam','Có')
    INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,SDT,GIOITINH,KHTT) VALUES(1,'Trần Thiên Đạt','TP.HCM','093472005673','Nam','Có')
    INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,SDT,GIOITINH,KHTT) VALUES(2,'Chương Do Minh','TP.HCM','093472005673','Nam','Không')
    INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,SDT,GIOITINH,KHTT) VALUES(3,'Trần Trương Minh Nghĩa','TP.HCM','093472005673','Nam','Không')
    INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,SDT,GIOITINH,KHTT) VALUES(4,'Tô Nguyễn Minh Khoa','TP.HCM','093472005673','Nam','Không')
    
    --NHAN VIEN
    INSERT INTO NHANVIEN(MANV,TENNV,GIOITINH,chucvu,SDT,TK,MK,trangthai) 
    VALUES(0,'Phan Chí Dũng','Nam','Nhân viên','093472005673','admin','123','Không hoạt động')
    INSERT INTO NHANVIEN(MANV,TENNV,GIOITINH,chucvu,SDT,TK,MK,trangthai) 
    VALUES(1,'Trần Thiên Đạt','Nam','Nhân viên','093472005673','admin','123','Hoạt động')
    INSERT INTO NHANVIEN(MANV,TENNV,GIOITINH,chucvu,SDT,TK,MK,trangthai) 
    VALUES(2,'Chương Do Minh','Nam','Nhân viên','093472005673','admin','123','Hoạt động')
    INSERT INTO NHANVIEN(MANV,TENNV,GIOITINH,chucvu,SDT,TK,MK,trangthai) 
    VALUES(3,'Trần Trương Minh Nghĩa','Nam','Quản lý','093472005673','admin','123','Không hoạt động')
    INSERT INTO NHANVIEN(MANV,TENNV,GIOITINH,chucvu,SDT,TK,MK,trangthai) 
    VALUES(4,'Tô Nguyễn Minh Khoa','Nam','Quản lý','093472005673','admin','123','Hoạt động')
    
    --NHA CUNG CAP
    INSERT INTO NHACUNGCAP(MANCC,TENNCC,SPCC,DIACHI,SDT) VALUES(0,'Biti's','Giày','TP.HCM','093472005673')
    INSERT INTO NHACUNGCAP(MANCC,TENNCC,SPCC,DIACHI,SDT) VALUES(1,'Kim Thành','Giày','TP.HCM','093472005673')
    INSERT INTO NHACUNGCAP(MANCC,TENNCC,SPCC,DIACHI,SDT) VALUES(2,'Biti's','Phụ kiện','TP.HCM','093472005673')
    
    --KHUYEN MAI
    INSERT INTO KHUYENMAI(MAKM,TENKM,HTKM,MUCKM,NGAYBD,NGAYKT) VALUES(0,'Sale mùa hè','Tiền',50000,'01/06/2022','08/06/2022')
    INSERT INTO KHUYENMAI(MAKM,TENKM,HTKM,MUCKM,NGAYBD,NGAYKT) VALUES(1,'Sale 25/6','Tiền',100000,'25/06/2022','30/06/2022')
   	INSERT INTO KHUYENMAI(MAKM,TENKM,HTKM,MUCKM,NGAYBD,NGAYKT) VALUES(2,'Mùa tựu trường','Tiền',150000,'01/09/2022','10/09/2022')

	--PHIEU NHAP
    INSERT INTO PHIEUNHAP(MAPN,NGAYLAP,TONGTIEN,MANV,MANCC) VALUES(0,'01/01/2022',10000000,0,0)
    INSERT INTO PHIEUNHAP(MAPN,NGAYLAP,TONGTIEN,MANV,MANCC) VALUES(1,'01/02/2022',25000000,1,1)
    INSERT INTO PHIEUNHAP(MAPN,NGAYLAP,TONGTIEN,MANV,MANCC) VALUES(2,'01/03/2022',10000000,2,2)
    INSERT INTO PHIEUNHAP(MAPN,NGAYLAP,TONGTIEN,MANV,MANCC) VALUES(3,'01/04/2022',15000000,3,3)


	SELECT * FROM GIAY WHERE MASP=3 AND TENSP=N'hehe' and soluong=2 and giaban=232

		update @giay
		set soluong=  100
		where MASP=1

		UPDATE giay SET SOLUONG =999 WHERE MASP =1